@startuml

header tomcat-9.0.30

title start the background thread that will periodically check for session timeouts

AbstractEndpoint -> Nio2Endpoint++: startInternal()

AbstractEndpoint <-- Nio2Endpoint--

@enduml