@startuml

header tomcat-9.0.30

title tomcat 启动过程

actor App
App -> Bootstrap++: main()
  Bootstrap -> Bootstrap++: new Bootstrap(),init(),设置daemon
    Bootstrap -> Bootstrap++: initClassLoaders()
    note right
    初始化classLoader
    根据catalina.properties配置文件创建对应的classLoader:
    commonLoader: 根据配置的common.loader来创建, 若无配置,
      取this.getClass().getClassLoader(),否则最终为URLClassLoader
    catalinaLoader: 根据配置的server.loader来创建, 默认没配置, 取commonLoader
    sharedLoader: 根据配置的shared.loader来创建, 默认没配置, 取commonLoader
    end note
    Bootstrap <-- Bootstrap--

  note right
  创建启动实例,设置其父类加载器为sharedLoader：
  Class<?> startupClass = catalinaLoader.loadClass("org.apache.catalina.startup.Catalina");
  Object startupInstance = startupClass.getConstructor().newInstance();
  catalinaDaemon =  startupInstance
  end note
  Bootstrap <-- Bootstrap--

    Bootstrap -> Bootstrap++: load(args)
        note right
        load daemon: 通过反射调用catalinaDaemon的load方法
        end note

        Bootstrap -> Catalina++: load(args)
            Catalina -> Catalina++: load(),启动一个server实例
                Catalina -> Catalina++: initDirs()
                deactivate Catalina

                Catalina -> Catalina++: initNaming()
                deactivate Catalina

                Catalina -> Catalina++:  createStartDigester()
                    note left
                    创建用来解析server.xml文件的Digester

                    见tomcat_load_createStartDigester.puml
                    end note
                Catalina <-- Catalina--:  Digester digester

                Catalina -> Digester++: digester.push(this);parse(inputSource)
                    note left
                    解析server.xml文件,创建对应的类

                    end note
                deactivate Digester

                Catalina -> Catalina++
                    note left
                    getServer().setCatalina(this);
                    getServer().setCatalinaHome(Bootstrap.getCatalinaHomeFile());
                    getServer().setCatalinaBase(Bootstrap.getCatalinaBaseFile());
                    end note
                deactivate Catalina

                Catalina -> Catalina++: initStreams()
                deactivate Catalina

                Catalina -> StandardServer++: getServer().init();
                    note left
                    见server_init.puml
                    end note
                deactivate StandardServer
            deactivate Catalina
        Bootstrap <-- Catalina--
    Bootstrap <-- Bootstrap--

    Bootstrap -> Bootstrap++: start()
        Bootstrap -> Catalina++: start()
            Catalina -> StandardServer++: getServer().start();
                note left
                见server_start.puml
                end note
            deactivate StandardServer
        deactivate Catalina
    deactivate Bootstrap
@enduml